### PR TITLE
Add standard deviation.

### LINKED ISSUE #6: Show confidence interval around chart points
Here are some notes about plotly examples:

## 1. https://plotly.com/javascript/error-bars/

[image](https://plotly.com/javascript/error-bars/)

relevant portion of code:

```js
error_y: { // <-- TODO: check compatibility with "scattergl" traces
  type: 'data',
  symmetric: false,
  array: [0.1, 0.2, 0.1, 0.1],
  arrayminus: [0.2, 0.4, 1, 0.2]
},
..
type: 'scatter',
```

## 2. https://plotly.com/javascript/continuous-error-bars/

[image](https://plotly.com/javascript/continuous-error-bars/)

relevant portion of code:

```js
var trace1 = {
  x: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1], 
  y: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0], 
  fill: "tozerox", 
  fillcolor: "rgba(0,100,80,0.2)", 
  line: {color: "transparent"}, 
  name: "Fair", 
  showlegend: false, // <-- NB pretty much the same as "trace4", but with a hidden legend
  type: "scatter"
};
```
```js
var trace3 = {
  x: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1], 
  y: [11, 9, 7, 5, 3, 1, 3, 5, 3, 1, -1, 1, 3, 1, -0.5, 1, 3, 5, 7, 9], 
  fill: "tozerox", 
  fillcolor: "rgba(231,107,243,0.2)", 
  line: {color: "transparent"}, 
  name: "Fair", 
  showlegend: false,  // <-- NB pretty much the same as "trace4", but with a hidden legend 
  type: "scatter"
};
```
```js
var trace4 = {
  x: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
  y: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 
  line: {color: "rgb(0,100,80)"}, 
  mode: "lines", 
  name: "Fair", 
  type: "scatter"
};
```

### PR DESCRIPTION
**Pull request by wlorenzetti**
closes: #6 

Add new option for Standard Deviation management:

Screenshot_20240108_113428

if Standard deviation is checked, on `qpstimeseries-api-plot-data` is added the following section `error_y`:

Screenshot_20240108_113804

### CODE REVIEW

**Comment by wlorenzetti** [comment]
@Raruto it seems not works fine, could you check? Thanks.

**Comment by Raruto** [comment]
@wlorenzetti I get this error on this form fields:

image

```log
Internal Server Error: /qps_timeseries/api/layerinfo/1/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/code/g3w-admin/core/api/base/views.py", line 182, in dispatch
    return super(G3WAPIView, self).dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/shared-volume/plugins/g3w-admin-ps-timeseries/qps_timeseries/api/views.py", line 66, in get
    self.results.update(get_base_plot_data(qfeature, qlayer))
  File "/shared-volume/plugins/g3w-admin-ps-timeseries/qps_timeseries/utils/data.py", line 70, in get_base_plot_data
    if qps_timeseries_layer.std:
AttributeError: 'NoneType' object has no attribute 'std'
```


```sh
python3 /code/g3w-admin/manage.py showmigrations
```

```log
qps_timeseries
 [X] 0001_initial
 [X] 0002_auto_20231213_1007
 [X] 0003_auto_20231214_1524
 [X] 0004_alter_qpstimeserieslayer_qps_timeseries_project
 [X] 0005_alter_qpstimeserieslayer_title_part_2
 [X] 0006_auto_20231228_1022
 [X] 0007_qpstimeserieslayer_std
```

**Comment by wlorenzetti** [comment]
@Raruto try it now.

**Comment by Raruto** [comment]
@wlorenzetti is it good enough?

image

**Comment by wlorenzetti** [comment]
It's fine thanks

**Pull request merged**
